package AST;

public enum NodeType {
    COMPUNIT, CONSTDECL, VARDECL, FUNCDEF, MAINFUNCDEF, CONSTDEF, VARDEF, FUNCFPARAMS, UNARYOP,
    CONSTEXP, CONSTINITVAL, INITVAL, FUNCFPARAM, ADDEXP, EXP, STMT, MULEXP, UNARYEXP, FUNCTYPE,
    PRIMARYEXP, FUNCRPARAMS, COND, LOREXP, LANDEXP, EQEXP, RELEXP, LVAL, BLOCK, TERMINAL, NUMBER,
}